### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Tuvqlu** [Theslowaja/TGCapes#2]
Hello, when I add new capes, it says I don’t have permission to use. How can I make permission

**Comment by Theslowaja** [comment]
you can use pureperm to add permissions for player
I will update it so that operator players don't bother adding one by one

**Comment by Tuvqlu** [comment]
What is the exact permission for each one? Just cape name?

**Comment by Theslowaja** [comment]
yes the name of the cape that you entered into the resource example: (emo.cape)  
and the plugin that I updated is ready so you can use the latest one

**Comment by Tuvqlu** [comment]
I’m using it and it still says I need permission

**Comment by Theslowaja** [comment]
what dev build are you using?
and are you op?

**Comment by Tuvqlu** [comment]
Ohh, just saw the new dev build. Works great!
