### ISSUE TITLE
Doesnt load onto my server

### ISSUE THREAD

**Issue by logannn61** [Theslowaja/TGCapes#3]
[Server thread/ERROR]: Could not load plugin 'TGCapes': Required PHP extension 'gd' is not loaded

**Comment by Theslowaja** [comment]
you should setup gd_library on your server

**Comment by logannn61** [comment]
> you should setup gd_library on your server

I do have it setup and the plugin still wont load

**Comment by Theslowaja** [comment]
idk my server is not like that

**Comment by RagnarTeam** [comment]
do you have discord??
 - what program do you use to create it a capes? -
